# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fitflavors
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fitflavors
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fitflavors-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    ENCRYPT_SALTS: ${env:ENCRYPT_SALTS}
  httpApi:
    authorizers:
      authorizer:
        type: request
        functionName: authorizer
        resultTtlInSeconds: 300
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  authorizer:
    handler: src/infra/functions/authorizer.handler

  signin:
    handler: src/infra/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post

  signup:
    handler: src/infra/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post

  profile:
    handler: src/infra/functions/profile.handler
    events:
      - httpApi:
          path: /me
          method: get
          authorizer:
            name: authorizer
            identitySource: $request.header.Authorization

  meal:
    handler: src/infra/functions/meal.handler
    events:
      - httpApi:
          path: /meals
          method: post
          authorizer:
            name: authorizer
            identitySource: $request.header.Authorization

  listMeals:
    handler: src/infra/functions/list-meals.handler
    events:
      - httpApi:
          path: /meals
          method: get
          authorizer:
            name: authorizer
            identitySource: $request.header.Authorization

  fetchMeal:
    handler: src/infra/functions/fetch-meal.handler
    events:
      - httpApi:
          path: /meals/{id}
          method: get
          authorizer:
            name: authorizer
            identitySource: $request.header.Authorization
